# Site settings
title: codeHEAD 
email: filipebsb04@gmail.com
description: Compartilhando conhecimento!
baseurl: "" 
url: "http://filipe-caf.github.io"

author:
  name     : 'Filipe Fernandes'
  email    : filipebsb04@gmail.com
  url      : http://filipe-caf.github.io
  facebook : http://facebook.com/filipe.caf
  github   : https://github.com/filipe-caf


disqus_shortname: "codeHEAD"
google_analytics: UA-52446115-1

paginate: 5
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
